# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApplicationSetup(object):
    def setupUi(self, ApplicationSetup):
        ApplicationSetup.setObjectName("ApplicationSetup")
        ApplicationSetup.resize(430, 230)
        self.verticalLayout = QtWidgets.QVBoxLayout(ApplicationSetup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_url = QtWidgets.QLabel(parent=ApplicationSetup)
        self.label_url.setObjectName("label_url")
        self.verticalLayout.addWidget(self.label_url)
        self.lineEdit_url = QtWidgets.QLineEdit(parent=ApplicationSetup)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.verticalLayout.addWidget(self.lineEdit_url)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_file = QtWidgets.QLabel(parent=ApplicationSetup)
        self.label_file.setObjectName("label_file")
        self.verticalLayout.addWidget(self.label_file)
        self.selectFileButton = QtWidgets.QPushButton(parent=ApplicationSetup)
        self.selectFileButton.setObjectName("selectFileButton")
        self.verticalLayout.addWidget(self.selectFileButton)
        self.selectedFileLabel = QtWidgets.QLabel(parent=ApplicationSetup)
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.verticalLayout.addWidget(self.selectedFileLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ApplicationSetup)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ApplicationSetup)
        self.buttonBox.accepted.connect(ApplicationSetup.accept) # type: ignore
        self.buttonBox.rejected.connect(ApplicationSetup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ApplicationSetup)

    def retranslateUi(self, ApplicationSetup):
        _translate = QtCore.QCoreApplication.translate
        ApplicationSetup.setWindowTitle(_translate("ApplicationSetup", "Application Setup"))
        self.label_url.setText(_translate("ApplicationSetup", "Please enter your database URL :"))
        self.lineEdit_url.setPlaceholderText(_translate("ApplicationSetup", "https://example.com"))
        self.label_file.setText(_translate("ApplicationSetup", "Please provide your Firebase Admin Credentials (.json) :"))
        self.selectFileButton.setText(_translate("ApplicationSetup", "Select"))
        self.selectedFileLabel.setText(_translate("ApplicationSetup", "No file selected."))
