# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommandLineTool(object):
    def setupUi(self, SafePaste):
        SafePaste.setObjectName("SafePaste")
        SafePaste.setGeometry(QtCore.QRect(0, 0, 420, 300))
        self.centralwidget = QtWidgets.QWidget(parent=SafePaste)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modeTabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.modeTabWidget.setObjectName("modeTabWidget")
        self.sendTab = QtWidgets.QWidget()
        self.sendTab.setObjectName("sendTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sendTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sendTextEdit = QtWidgets.QTextEdit(parent=self.sendTab)
        self.sendTextEdit.setObjectName("sendTextEdit")
        self.verticalLayout_2.addWidget(self.sendTextEdit)
        self.sendButton = QtWidgets.QPushButton(parent=self.sendTab)
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout_2.addWidget(self.sendButton)
        self.idLayout = QtWidgets.QHBoxLayout()
        self.idLayout.setObjectName("idLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.idLayout.addItem(spacerItem)
        self.idLabel = QtWidgets.QLabel(parent=self.sendTab)
        self.idLabel.setObjectName("idLabel")
        self.idLayout.addWidget(self.idLabel)
        self.clipboardButton = QtWidgets.QToolButton(parent=self.sendTab)
        self.clipboardButton.setObjectName("clipboardButton")
        self.idLayout.addWidget(self.clipboardButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.idLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.idLayout)
        self.modeTabWidget.addTab(self.sendTab, "")
        self.receiveTab = QtWidgets.QWidget()
        self.receiveTab.setObjectName("receiveTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.receiveTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.receiveTextEdit = QtWidgets.QTextEdit(parent=self.receiveTab)
        self.receiveTextEdit.setReadOnly(True)
        self.receiveTextEdit.setObjectName("receiveTextEdit")
        self.verticalLayout_3.addWidget(self.receiveTextEdit)
        self.fetchLayout = QtWidgets.QHBoxLayout()
        self.fetchLayout.setObjectName("fetchLayout")
        self.codeLineEdit = QtWidgets.QLineEdit(parent=self.receiveTab)
        self.codeLineEdit.setObjectName("codeLineEdit")
        self.fetchLayout.addWidget(self.codeLineEdit)
        self.fetchButton = QtWidgets.QPushButton(parent=self.receiveTab)
        self.fetchButton.setObjectName("fetchButton")
        self.fetchLayout.addWidget(self.fetchButton)
        self.verticalLayout_3.addLayout(self.fetchLayout)
        self.modeTabWidget.addTab(self.receiveTab, "")
        self.verticalLayout.addWidget(self.modeTabWidget)
        self.githubLink = QtWidgets.QLabel(parent=self.centralwidget)
        self.githubLink.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.githubLink.setOpenExternalLinks(True)
        self.githubLink.setObjectName("githubLink")
        self.verticalLayout.addWidget(self.githubLink)
        SafePaste.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SafePaste)
        self.menubar.setObjectName("menubar")
        SafePaste.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SafePaste)
        self.statusbar.setObjectName("statusbar")
        SafePaste.setStatusBar(self.statusbar)

        self.retranslateUi(SafePaste)
        self.modeTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SafePaste)

    def retranslateUi(self, SafePaste):
        _translate = QtCore.QCoreApplication.translate
        SafePaste.setWindowTitle(_translate("CommandLineTool", "SafePaste"))
        SafePaste.setStyleSheet(_translate("CommandLineTool", "\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"QTextEdit, QLineEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
""))
        self.sendTextEdit.setPlaceholderText(_translate("CommandLineTool", "Enter data to send..."))
        self.sendButton.setText(_translate("CommandLineTool", "SEND"))
        self.idLabel.setText(_translate("CommandLineTool", "ID - "))
        self.clipboardButton.setText(_translate("CommandLineTool", "Copy"))
        self.modeTabWidget.setTabText(self.modeTabWidget.indexOf(self.sendTab), _translate("CommandLineTool", "SEND"))
        self.receiveTextEdit.setPlaceholderText(_translate("CommandLineTool", "Received data will appear here..."))
        self.codeLineEdit.setPlaceholderText(_translate("CommandLineTool", "Enter the unique ID!!"))
        self.fetchButton.setText(_translate("CommandLineTool", "FETCH"))
        self.modeTabWidget.setTabText(self.modeTabWidget.indexOf(self.receiveTab), _translate("CommandLineTool", "RECEIVE"))
        self.githubLink.setText(_translate("CommandLineTool", "<a href=\"https://github.com/S1ddhaarth/SafePaste\">Source Code</a>"))
